name: "Build Android app"

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Install node JS
      #   uses: actions/setup-node@v4
      #   with:
      #     node-vesion: 18

      # - name: install firebase cli
      #   run: npm install -g firebase-tools

      # - name: Authenticate with firebase
      #   run: firebase login:ci

      - name: Download Files from Firebase Storage
        run: curl 'https://firebasestorage.googleapis.com/v0/b/${{secrets.FIREBASE_BUCKET}}/o/${{secrets.FIREBASE_FILE}}?alt=media&token=${{secrets.FIREBASE_TOKEN}}' -o ${{secrets.FIREBASE_FILE}}
        # run: firebase storage:download --token "${{secrets.FIREBASE_TOKEN}}" --output ./downloaded-files gs://search-list-c9007.appspot.com/prod.keystore

      - name: Upload file to artificate
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: Downloads/prod.keystore
          retention-days: 1
# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install Java
#         uses: actions/setup-java@v3
#         with:
#           java-version: 11
#           distribution: adopt
#           cache: gradle

#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@v1

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "18"
#           cache: "npm"

#       - name: Install React Native CLI
#         run: npm install -g react-native-cli

#       - name: Run NPM Install
#         run:  npm i

#       - name: Create release build
#         run: |
#           cd android
#           ./gradlew assembleRelease

#       - name: Upload application
#         uses: actions/upload-artifact@v4
#         with:
#           name: app
#           path: android/app/build/outputs/apk/release/app-release.apk
#           retention-days: 3
