name: "Build Android app"

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  donwload-keystore:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Files from Firebase Storage
        run: curl 'https://firebasestorage.googleapis.com/v0/b/${{secrets.FIREBASE_BUCKET}}/o/${{secrets.FIREBASE_FILE}}?alt=media&token=${{secrets.FIREBASE_BUCKET_TOKEN}}' -o ./android/app/${{secrets.FIREBASE_FILE}}

      - name: Upload file to artificate
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: android/app/${{secrets.FIREBASE_FILE}}
          retention-days: 1

  build-app:
    needs: donwload-keystore
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      # - name: Install React Native CLI
      #   run: npm install -g react-native-cli

      - name: Run NPM Install
        run:  npm i

      - name: Create release build
        run: |
          cd android
          ./gradlew assembleRelease

      # - name: Oprimize the apk
      #   run: |
      #     cd android/app/build/outputs/apk
      #     zipalign -p -f -v 4 app-release.apk app-release-optimized.apk

      # - name: Sign the apk
      #   run: apksigner sign --ks android/app/${{secrets.FIREBASE_FILE}} --out app.apk app-release-optimized.apk

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: android/app/build/outputs/apk/release/app-release.apk
          retention-days: 1

  upload-app: 
    needs: build-app
    runs-on: macos-latest
    steps:
      - name: Install firebase CLI
        run: npm i -g firebase-tools

      - name: Upload apk
        run: firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk --app ${{secrets.FIREBASE_APP_ID}} --token ${{secrets.FIREBASE_TOKEN}} --release-notes "First app distribute" --testers "www.ankurjyotidas333@gmail.com"

# firebase appdistribution:distribute test.apk  \
#     --app 1:1234567890:android:0a1b2c3d4e5f67890  \
#     --release-notes "Bug fixes and improvements" --testers-file testers.txt

# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Install Java
#         uses: actions/setup-java@v3
#         with:
#           java-version: 11
#           distribution: adopt
#           cache: gradle

#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@v1

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: "18"
#           cache: "npm"

#       - name: Install React Native CLI
#         run: npm install -g react-native-cli

#       - name: Run NPM Install
#         run:  npm i

#       - name: Create release build
#         run: |
#           cd android
#           ./gradlew assembleRelease

#       - name: Upload application
#         uses: actions/upload-artifact@v4
#         with:
#           name: app
#           path: android/app/build/outputs/apk/release/app-release.apk
#           retention-days: 3
